<?php

namespace DoctrineORMModule\Proxy\__CG__\API\V1\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Distributor extends \API\V1\Entity\Distributor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'id', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'user', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'distributor', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'distributors', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'clinics', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'master'];
        }

        return ['__isInitialized__', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'id', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'user', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'distributor', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'distributors', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'clinics', '' . "\0" . 'API\\V1\\Entity\\Distributor' . "\0" . 'master'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Distributor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addClinic(\API\V1\Entity\Clinic $clinic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClinic', [$clinic]);

        return parent::addClinic($clinic);
    }

    /**
     * {@inheritDoc}
     */
    public function addDistributor(\API\V1\Entity\Distributor $distributor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDistributor', [$distributor]);

        return parent::addDistributor($distributor);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinicsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinicsCount', []);

        return parent::getClinicsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getPetsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetsCount', []);

        return parent::getPetsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistributor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistributor', []);

        return parent::getDistributor();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistributors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistributors', []);

        return parent::getDistributors();
    }

    /**
     * {@inheritDoc}
     */
    public function getClinics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinics', []);

        return parent::getClinics();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDistributor($distributor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistributor', [$distributor]);

        return parent::setDistributor($distributor);
    }

    /**
     * {@inheritDoc}
     */
    public function setDistributors($distributors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistributors', [$distributors]);

        return parent::setDistributors($distributors);
    }

    /**
     * {@inheritDoc}
     */
    public function setClinics($clinics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinics', [$clinics]);

        return parent::setClinics($clinics);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaster()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaster', []);

        return parent::getMaster();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaster($master)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaster', [$master]);

        return parent::setMaster($master);
    }

}
