<?php

namespace DoctrineORMModule\Proxy\__CG__\API\V1\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pet extends \API\V1\Entity\Pet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'id', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'name', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'sex', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'birthdate', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'color', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'orign', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'pedigree', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'microchip', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'qrCode', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'creation', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'race', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'specie', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'owner', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'employee', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'manager', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'photo', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'clinics', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'deleted', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'groomings', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'histories', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'historiesPdf'];
        }

        return ['__isInitialized__', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'id', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'name', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'sex', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'birthdate', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'color', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'orign', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'pedigree', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'microchip', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'qrCode', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'creation', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'race', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'specie', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'owner', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'employee', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'manager', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'photo', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'clinics', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'deleted', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'groomings', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'histories', '' . "\0" . 'API\\V1\\Entity\\Pet' . "\0" . 'historiesPdf'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addHistory(\API\V1\Entity\History $history)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistory', [$history]);

        return parent::addHistory($history);
    }

    /**
     * {@inheritDoc}
     */
    public function addClinic(\API\V1\Entity\Clinic $clinic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClinic', [$clinic]);

        return parent::addClinic($clinic);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', []);

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrign()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrign', []);

        return parent::getOrign();
    }

    /**
     * {@inheritDoc}
     */
    public function getPedigree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedigree', []);

        return parent::getPedigree();
    }

    /**
     * {@inheritDoc}
     */
    public function getQrCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQrCode', []);

        return parent::getQrCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreation', []);

        return parent::getCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function getHistories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistories', []);

        return parent::getHistories();
    }

    /**
     * {@inheritDoc}
     */
    public function getRace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRace', []);

        return parent::getRace();
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecie', []);

        return parent::getSpecie();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function getManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManager', []);

        return parent::getManager();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getClinics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinics', []);

        return parent::getClinics();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthdate($birthdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthdate', [$birthdate]);

        return parent::setBirthdate($birthdate);
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrign($orign)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrign', [$orign]);

        return parent::setOrign($orign);
    }

    /**
     * {@inheritDoc}
     */
    public function setPedigree($pedigree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPedigree', [$pedigree]);

        return parent::setPedigree($pedigree);
    }

    /**
     * {@inheritDoc}
     */
    public function setQrCode($qrCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQrCode', [$qrCode]);

        return parent::setQrCode($qrCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreation($creation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreation', [$creation]);

        return parent::setCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function setHistories($histories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistories', [$histories]);

        return parent::setHistories($histories);
    }

    /**
     * {@inheritDoc}
     */
    public function setRace($race)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRace', [$race]);

        return parent::setRace($race);
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecie($specie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecie', [$specie]);

        return parent::setSpecie($specie);
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\API\V1\Entity\Owner $owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee($employee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        return parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function setManager($manager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManager', [$manager]);

        return parent::setManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function setClinics($clinics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinics', [$clinics]);

        return parent::setClinics($clinics);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMicrochip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMicrochip', []);

        return parent::getMicrochip();
    }

    /**
     * {@inheritDoc}
     */
    public function setMicrochip($microchip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMicrochip', [$microchip]);

        return parent::setMicrochip($microchip);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroomings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroomings', []);

        return parent::getGroomings();
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoriesPdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoriesPdf', []);

        return parent::getHistoriesPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroomings($groomings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroomings', [$groomings]);

        return parent::setGroomings($groomings);
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoriesPdf($historiesPdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoriesPdf', [$historiesPdf]);

        return parent::setHistoriesPdf($historiesPdf);
    }

}
